package com.evisible.os.controlcenter.system.entity;

import java.util.Date;

public class SDicDate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_dic_date.uuid
     *
     * @mbggenerated Mon Apr 25 16:38:45 CST 2016
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_dic_date.typecode
     *
     * @mbggenerated Mon Apr 25 16:38:45 CST 2016
     */
    private String typecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_dic_date.d_name
     *
     * @mbggenerated Mon Apr 25 16:38:45 CST 2016
     */
    private String dName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_dic_date.d_value
     *
     * @mbggenerated Mon Apr 25 16:38:45 CST 2016
     */
    private String dValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_dic_date.creator
     *
     * @mbggenerated Mon Apr 25 16:38:45 CST 2016
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_dic_date.createdate
     *
     * @mbggenerated Mon Apr 25 16:38:45 CST 2016
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_dic_date.updator
     *
     * @mbggenerated Mon Apr 25 16:38:45 CST 2016
     */
    private String updator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_dic_date.updatedate
     *
     * @mbggenerated Mon Apr 25 16:38:45 CST 2016
     */
    private Date updatedate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_dic_date.uuid
     *
     * @return the value of s_dic_date.uuid
     *
     * @mbggenerated Mon Apr 25 16:38:45 CST 2016
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_dic_date.uuid
     *
     * @param uuid the value for s_dic_date.uuid
     *
     * @mbggenerated Mon Apr 25 16:38:45 CST 2016
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_dic_date.typecode
     *
     * @return the value of s_dic_date.typecode
     *
     * @mbggenerated Mon Apr 25 16:38:45 CST 2016
     */
    public String getTypecode() {
        return typecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_dic_date.typecode
     *
     * @param typecode the value for s_dic_date.typecode
     *
     * @mbggenerated Mon Apr 25 16:38:45 CST 2016
     */
    public void setTypecode(String typecode) {
        this.typecode = typecode == null ? null : typecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_dic_date.d_name
     *
     * @return the value of s_dic_date.d_name
     *
     * @mbggenerated Mon Apr 25 16:38:45 CST 2016
     */
    public String getdName() {
        return dName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_dic_date.d_name
     *
     * @param dName the value for s_dic_date.d_name
     *
     * @mbggenerated Mon Apr 25 16:38:45 CST 2016
     */
    public void setdName(String dName) {
        this.dName = dName == null ? null : dName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_dic_date.d_value
     *
     * @return the value of s_dic_date.d_value
     *
     * @mbggenerated Mon Apr 25 16:38:45 CST 2016
     */
    public String getdValue() {
        return dValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_dic_date.d_value
     *
     * @param dValue the value for s_dic_date.d_value
     *
     * @mbggenerated Mon Apr 25 16:38:45 CST 2016
     */
    public void setdValue(String dValue) {
        this.dValue = dValue == null ? null : dValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_dic_date.creator
     *
     * @return the value of s_dic_date.creator
     *
     * @mbggenerated Mon Apr 25 16:38:45 CST 2016
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_dic_date.creator
     *
     * @param creator the value for s_dic_date.creator
     *
     * @mbggenerated Mon Apr 25 16:38:45 CST 2016
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_dic_date.createdate
     *
     * @return the value of s_dic_date.createdate
     *
     * @mbggenerated Mon Apr 25 16:38:45 CST 2016
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_dic_date.createdate
     *
     * @param createdate the value for s_dic_date.createdate
     *
     * @mbggenerated Mon Apr 25 16:38:45 CST 2016
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_dic_date.updator
     *
     * @return the value of s_dic_date.updator
     *
     * @mbggenerated Mon Apr 25 16:38:45 CST 2016
     */
    public String getUpdator() {
        return updator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_dic_date.updator
     *
     * @param updator the value for s_dic_date.updator
     *
     * @mbggenerated Mon Apr 25 16:38:45 CST 2016
     */
    public void setUpdator(String updator) {
        this.updator = updator == null ? null : updator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_dic_date.updatedate
     *
     * @return the value of s_dic_date.updatedate
     *
     * @mbggenerated Mon Apr 25 16:38:45 CST 2016
     */
    public Date getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_dic_date.updatedate
     *
     * @param updatedate the value for s_dic_date.updatedate
     *
     * @mbggenerated Mon Apr 25 16:38:45 CST 2016
     */
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }
}