package com.evisible.os.controlcenter.system.entity;

import java.util.Date;

public class SFun {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_fun.uuid
     *
     * @mbggenerated Tue Mar 29 14:38:29 CST 2016
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_fun.f_name
     *
     * @mbggenerated Tue Mar 29 14:38:29 CST 2016
     */
    private String fName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_fun.f_name_jx
     *
     * @mbggenerated Tue Mar 29 14:38:29 CST 2016
     */
    private String fNameJx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_fun.fun_type
     *
     * @mbggenerated Tue Mar 29 14:38:29 CST 2016
     */
    private String funType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_fun.sort_index
     *
     * @mbggenerated Tue Mar 29 14:38:29 CST 2016
     */
    private Integer sortIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_fun.pater_id
     *
     * @mbggenerated Tue Mar 29 14:38:29 CST 2016
     */
    private String paterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_fun.url
     *
     * @mbggenerated Tue Mar 29 14:38:29 CST 2016
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_fun.creator
     *
     * @mbggenerated Tue Mar 29 14:38:29 CST 2016
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_fun.createdate
     *
     * @mbggenerated Tue Mar 29 14:38:29 CST 2016
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_fun.updator
     *
     * @mbggenerated Tue Mar 29 14:38:29 CST 2016
     */
    private String updator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_fun.updatedate
     *
     * @mbggenerated Tue Mar 29 14:38:29 CST 2016
     */
    private Date updatedate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_fun.uuid
     *
     * @return the value of s_fun.uuid
     *
     * @mbggenerated Tue Mar 29 14:38:29 CST 2016
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_fun.uuid
     *
     * @param uuid the value for s_fun.uuid
     *
     * @mbggenerated Tue Mar 29 14:38:29 CST 2016
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_fun.f_name
     *
     * @return the value of s_fun.f_name
     *
     * @mbggenerated Tue Mar 29 14:38:29 CST 2016
     */
    public String getfName() {
        return fName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_fun.f_name
     *
     * @param fName the value for s_fun.f_name
     *
     * @mbggenerated Tue Mar 29 14:38:29 CST 2016
     */
    public void setfName(String fName) {
        this.fName = fName == null ? null : fName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_fun.f_name_jx
     *
     * @return the value of s_fun.f_name_jx
     *
     * @mbggenerated Tue Mar 29 14:38:29 CST 2016
     */
    public String getfNameJx() {
        return fNameJx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_fun.f_name_jx
     *
     * @param fNameJx the value for s_fun.f_name_jx
     *
     * @mbggenerated Tue Mar 29 14:38:29 CST 2016
     */
    public void setfNameJx(String fNameJx) {
        this.fNameJx = fNameJx == null ? null : fNameJx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_fun.fun_type
     *
     * @return the value of s_fun.fun_type
     *
     * @mbggenerated Tue Mar 29 14:38:29 CST 2016
     */
    public String getFunType() {
        return funType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_fun.fun_type
     *
     * @param funType the value for s_fun.fun_type
     *
     * @mbggenerated Tue Mar 29 14:38:29 CST 2016
     */
    public void setFunType(String funType) {
        this.funType = funType == null ? null : funType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_fun.sort_index
     *
     * @return the value of s_fun.sort_index
     *
     * @mbggenerated Tue Mar 29 14:38:29 CST 2016
     */
    public Integer getSortIndex() {
        return sortIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_fun.sort_index
     *
     * @param sortIndex the value for s_fun.sort_index
     *
     * @mbggenerated Tue Mar 29 14:38:29 CST 2016
     */
    public void setSortIndex(Integer sortIndex) {
        this.sortIndex = sortIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_fun.pater_id
     *
     * @return the value of s_fun.pater_id
     *
     * @mbggenerated Tue Mar 29 14:38:29 CST 2016
     */
    public String getPaterId() {
        return paterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_fun.pater_id
     *
     * @param paterId the value for s_fun.pater_id
     *
     * @mbggenerated Tue Mar 29 14:38:29 CST 2016
     */
    public void setPaterId(String paterId) {
        this.paterId = paterId == null ? null : paterId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_fun.url
     *
     * @return the value of s_fun.url
     *
     * @mbggenerated Tue Mar 29 14:38:29 CST 2016
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_fun.url
     *
     * @param url the value for s_fun.url
     *
     * @mbggenerated Tue Mar 29 14:38:29 CST 2016
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_fun.creator
     *
     * @return the value of s_fun.creator
     *
     * @mbggenerated Tue Mar 29 14:38:29 CST 2016
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_fun.creator
     *
     * @param creator the value for s_fun.creator
     *
     * @mbggenerated Tue Mar 29 14:38:29 CST 2016
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_fun.createdate
     *
     * @return the value of s_fun.createdate
     *
     * @mbggenerated Tue Mar 29 14:38:29 CST 2016
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_fun.createdate
     *
     * @param createdate the value for s_fun.createdate
     *
     * @mbggenerated Tue Mar 29 14:38:29 CST 2016
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_fun.updator
     *
     * @return the value of s_fun.updator
     *
     * @mbggenerated Tue Mar 29 14:38:29 CST 2016
     */
    public String getUpdator() {
        return updator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_fun.updator
     *
     * @param updator the value for s_fun.updator
     *
     * @mbggenerated Tue Mar 29 14:38:29 CST 2016
     */
    public void setUpdator(String updator) {
        this.updator = updator == null ? null : updator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_fun.updatedate
     *
     * @return the value of s_fun.updatedate
     *
     * @mbggenerated Tue Mar 29 14:38:29 CST 2016
     */
    public Date getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_fun.updatedate
     *
     * @param updatedate the value for s_fun.updatedate
     *
     * @mbggenerated Tue Mar 29 14:38:29 CST 2016
     */
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }
}