package com.evisible.os.controlcenter.system.entity;

import java.util.Date;

public class SOrgUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_org_user.uuid
     *
     * @mbggenerated Tue Aug 16 10:18:44 CST 2016
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_org_user.u_id
     *
     * @mbggenerated Tue Aug 16 10:18:44 CST 2016
     */
    private String uId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_org_user.org_id
     *
     * @mbggenerated Tue Aug 16 10:18:44 CST 2016
     */
    private String orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_org_user.creator
     *
     * @mbggenerated Tue Aug 16 10:18:44 CST 2016
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_org_user.createdate
     *
     * @mbggenerated Tue Aug 16 10:18:44 CST 2016
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_org_user.updator
     *
     * @mbggenerated Tue Aug 16 10:18:44 CST 2016
     */
    private String updator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_org_user.updatedate
     *
     * @mbggenerated Tue Aug 16 10:18:44 CST 2016
     */
    private Date updatedate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_org_user.uuid
     *
     * @return the value of s_org_user.uuid
     *
     * @mbggenerated Tue Aug 16 10:18:44 CST 2016
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_org_user.uuid
     *
     * @param uuid the value for s_org_user.uuid
     *
     * @mbggenerated Tue Aug 16 10:18:44 CST 2016
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_org_user.u_id
     *
     * @return the value of s_org_user.u_id
     *
     * @mbggenerated Tue Aug 16 10:18:44 CST 2016
     */
    public String getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_org_user.u_id
     *
     * @param uId the value for s_org_user.u_id
     *
     * @mbggenerated Tue Aug 16 10:18:44 CST 2016
     */
    public void setuId(String uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_org_user.org_id
     *
     * @return the value of s_org_user.org_id
     *
     * @mbggenerated Tue Aug 16 10:18:44 CST 2016
     */
    public String getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_org_user.org_id
     *
     * @param orgId the value for s_org_user.org_id
     *
     * @mbggenerated Tue Aug 16 10:18:44 CST 2016
     */
    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_org_user.creator
     *
     * @return the value of s_org_user.creator
     *
     * @mbggenerated Tue Aug 16 10:18:44 CST 2016
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_org_user.creator
     *
     * @param creator the value for s_org_user.creator
     *
     * @mbggenerated Tue Aug 16 10:18:44 CST 2016
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_org_user.createdate
     *
     * @return the value of s_org_user.createdate
     *
     * @mbggenerated Tue Aug 16 10:18:44 CST 2016
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_org_user.createdate
     *
     * @param createdate the value for s_org_user.createdate
     *
     * @mbggenerated Tue Aug 16 10:18:44 CST 2016
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_org_user.updator
     *
     * @return the value of s_org_user.updator
     *
     * @mbggenerated Tue Aug 16 10:18:44 CST 2016
     */
    public String getUpdator() {
        return updator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_org_user.updator
     *
     * @param updator the value for s_org_user.updator
     *
     * @mbggenerated Tue Aug 16 10:18:44 CST 2016
     */
    public void setUpdator(String updator) {
        this.updator = updator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_org_user.updatedate
     *
     * @return the value of s_org_user.updatedate
     *
     * @mbggenerated Tue Aug 16 10:18:44 CST 2016
     */
    public Date getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_org_user.updatedate
     *
     * @param updatedate the value for s_org_user.updatedate
     *
     * @mbggenerated Tue Aug 16 10:18:44 CST 2016
     */
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }
}