package com.evisible.os.controlcenter.system.entity;

import java.util.Date;
import java.util.List;

public class SOrg {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_org.uuid
     *
     * @mbggenerated Tue Aug 16 10:18:44 CST 2016
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_org.org_code
     *
     * @mbggenerated Tue Aug 16 10:18:44 CST 2016
     */
    private String orgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_org.org_name
     *
     * @mbggenerated Tue Aug 16 10:18:44 CST 2016
     */
    private String orgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_org.parent_code
     *
     * @mbggenerated Tue Aug 16 10:18:44 CST 2016
     */
    private String parentCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_org.parent_id
     *
     * @mbggenerated Tue Aug 16 10:18:44 CST 2016
     */
    private String parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_org.sort_index
     *
     * @mbggenerated Tue Aug 16 10:18:44 CST 2016
     */
    private Integer sortIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_org.locked
     *
     * @mbggenerated Tue Aug 16 10:18:44 CST 2016
     */
    private Long locked;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_org.creator
     *
     * @mbggenerated Tue Aug 16 10:18:44 CST 2016
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_org.createdate
     *
     * @mbggenerated Tue Aug 16 10:18:44 CST 2016
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_org.updator
     *
     * @mbggenerated Tue Aug 16 10:18:44 CST 2016
     */
    private String updator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_org.updatedate
     *
     * @mbggenerated Tue Aug 16 10:18:44 CST 2016
     */
    private Date updatedate;
    
    
    private List<SOrg> children;
    
    

    public final List<SOrg> getChildren() {
		return children;
	}

	public final void setChildren(List<SOrg> children) {
		this.children = children;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_org.uuid
     *
     * @return the value of s_org.uuid
     *
     * @mbggenerated Tue Aug 16 10:18:44 CST 2016
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_org.uuid
     *
     * @param uuid the value for s_org.uuid
     *
     * @mbggenerated Tue Aug 16 10:18:44 CST 2016
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_org.org_code
     *
     * @return the value of s_org.org_code
     *
     * @mbggenerated Tue Aug 16 10:18:44 CST 2016
     */
    public String getOrgCode() {
        return orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_org.org_code
     *
     * @param orgCode the value for s_org.org_code
     *
     * @mbggenerated Tue Aug 16 10:18:44 CST 2016
     */
    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_org.org_name
     *
     * @return the value of s_org.org_name
     *
     * @mbggenerated Tue Aug 16 10:18:44 CST 2016
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_org.org_name
     *
     * @param orgName the value for s_org.org_name
     *
     * @mbggenerated Tue Aug 16 10:18:44 CST 2016
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_org.parent_code
     *
     * @return the value of s_org.parent_code
     *
     * @mbggenerated Tue Aug 16 10:18:44 CST 2016
     */
    public String getParentCode() {
        return parentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_org.parent_code
     *
     * @param parentCode the value for s_org.parent_code
     *
     * @mbggenerated Tue Aug 16 10:18:44 CST 2016
     */
    public void setParentCode(String parentCode) {
        this.parentCode = parentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_org.parent_id
     *
     * @return the value of s_org.parent_id
     *
     * @mbggenerated Tue Aug 16 10:18:44 CST 2016
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_org.parent_id
     *
     * @param parentId the value for s_org.parent_id
     *
     * @mbggenerated Tue Aug 16 10:18:44 CST 2016
     */
    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_org.sort_index
     *
     * @return the value of s_org.sort_index
     *
     * @mbggenerated Tue Aug 16 10:18:44 CST 2016
     */
    public Integer getSortIndex() {
        return sortIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_org.sort_index
     *
     * @param sortIndex the value for s_org.sort_index
     *
     * @mbggenerated Tue Aug 16 10:18:44 CST 2016
     */
    public void setSortIndex(Integer sortIndex) {
        this.sortIndex = sortIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_org.locked
     *
     * @return the value of s_org.locked
     *
     * @mbggenerated Tue Aug 16 10:18:44 CST 2016
     */
    public Long getLocked() {
        return locked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_org.locked
     *
     * @param locked the value for s_org.locked
     *
     * @mbggenerated Tue Aug 16 10:18:44 CST 2016
     */
    public void setLocked(Long locked) {
        this.locked = locked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_org.creator
     *
     * @return the value of s_org.creator
     *
     * @mbggenerated Tue Aug 16 10:18:44 CST 2016
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_org.creator
     *
     * @param creator the value for s_org.creator
     *
     * @mbggenerated Tue Aug 16 10:18:44 CST 2016
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_org.createdate
     *
     * @return the value of s_org.createdate
     *
     * @mbggenerated Tue Aug 16 10:18:44 CST 2016
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_org.createdate
     *
     * @param createdate the value for s_org.createdate
     *
     * @mbggenerated Tue Aug 16 10:18:44 CST 2016
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_org.updator
     *
     * @return the value of s_org.updator
     *
     * @mbggenerated Tue Aug 16 10:18:44 CST 2016
     */
    public String getUpdator() {
        return updator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_org.updator
     *
     * @param updator the value for s_org.updator
     *
     * @mbggenerated Tue Aug 16 10:18:44 CST 2016
     */
    public void setUpdator(String updator) {
        this.updator = updator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_org.updatedate
     *
     * @return the value of s_org.updatedate
     *
     * @mbggenerated Tue Aug 16 10:18:44 CST 2016
     */
    public Date getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_org.updatedate
     *
     * @param updatedate the value for s_org.updatedate
     *
     * @mbggenerated Tue Aug 16 10:18:44 CST 2016
     */
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }
}