package com.evisible.os.controlcenter.system.entity;

import java.util.Date;

import com.evisible.os.controlcenter.model.Message;


public class SPermission extends Message{
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_permission.uuid
     *
     * @mbggenerated Mon Apr 18 09:45:30 CST 2016
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_permission.fun_id
     *
     * @mbggenerated Mon Apr 18 09:45:30 CST 2016
     */
    private String funId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_permission.role_id
     *
     * @mbggenerated Mon Apr 18 09:45:30 CST 2016
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_permission.p_name
     *
     * @mbggenerated Mon Apr 18 09:45:30 CST 2016
     */
    private String pName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_permission.permission
     *
     * @mbggenerated Mon Apr 18 09:45:30 CST 2016
     */
    private String permission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_permission.creator
     *
     * @mbggenerated Mon Apr 18 09:45:30 CST 2016
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_permission.createdate
     *
     * @mbggenerated Mon Apr 18 09:45:30 CST 2016
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_permission.updator
     *
     * @mbggenerated Mon Apr 18 09:45:30 CST 2016
     */
    private String updator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_permission.updatedate
     *
     * @mbggenerated Mon Apr 18 09:45:30 CST 2016
     */
    private Date updatedate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_permission.uuid
     *
     * @return the value of s_permission.uuid
     *
     * @mbggenerated Mon Apr 18 09:45:30 CST 2016
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_permission.uuid
     *
     * @param uuid the value for s_permission.uuid
     *
     * @mbggenerated Mon Apr 18 09:45:30 CST 2016
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_permission.fun_id
     *
     * @return the value of s_permission.fun_id
     *
     * @mbggenerated Mon Apr 18 09:45:30 CST 2016
     */
    public String getFunId() {
        return funId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_permission.fun_id
     *
     * @param funId the value for s_permission.fun_id
     *
     * @mbggenerated Mon Apr 18 09:45:30 CST 2016
     */
    public void setFunId(String funId) {
        this.funId = funId == null ? null : funId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_permission.role_id
     *
     * @return the value of s_permission.role_id
     *
     * @mbggenerated Mon Apr 18 09:45:30 CST 2016
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_permission.role_id
     *
     * @param roleId the value for s_permission.role_id
     *
     * @mbggenerated Mon Apr 18 09:45:30 CST 2016
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_permission.p_name
     *
     * @return the value of s_permission.p_name
     *
     * @mbggenerated Mon Apr 18 09:45:30 CST 2016
     */
    public String getpName() {
        return pName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_permission.p_name
     *
     * @param pName the value for s_permission.p_name
     *
     * @mbggenerated Mon Apr 18 09:45:30 CST 2016
     */
    public void setpName(String pName) {
        this.pName = pName == null ? null : pName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_permission.permission
     *
     * @return the value of s_permission.permission
     *
     * @mbggenerated Mon Apr 18 09:45:30 CST 2016
     */
    public String getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_permission.permission
     *
     * @param permission the value for s_permission.permission
     *
     * @mbggenerated Mon Apr 18 09:45:30 CST 2016
     */
    public void setPermission(String permission) {
        this.permission = permission == null ? null : permission.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_permission.creator
     *
     * @return the value of s_permission.creator
     *
     * @mbggenerated Mon Apr 18 09:45:30 CST 2016
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_permission.creator
     *
     * @param creator the value for s_permission.creator
     *
     * @mbggenerated Mon Apr 18 09:45:30 CST 2016
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_permission.createdate
     *
     * @return the value of s_permission.createdate
     *
     * @mbggenerated Mon Apr 18 09:45:30 CST 2016
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_permission.createdate
     *
     * @param createdate the value for s_permission.createdate
     *
     * @mbggenerated Mon Apr 18 09:45:30 CST 2016
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_permission.updator
     *
     * @return the value of s_permission.updator
     *
     * @mbggenerated Mon Apr 18 09:45:30 CST 2016
     */
    public String getUpdator() {
        return updator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_permission.updator
     *
     * @param updator the value for s_permission.updator
     *
     * @mbggenerated Mon Apr 18 09:45:30 CST 2016
     */
    public void setUpdator(String updator) {
        this.updator = updator == null ? null : updator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_permission.updatedate
     *
     * @return the value of s_permission.updatedate
     *
     * @mbggenerated Mon Apr 18 09:45:30 CST 2016
     */
    public Date getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_permission.updatedate
     *
     * @param updatedate the value for s_permission.updatedate
     *
     * @mbggenerated Mon Apr 18 09:45:30 CST 2016
     */
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }
}