package com.evisible.os.controlcenter.system.entity;

import java.util.Date;

public class SUserRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_role.uuid
     *
     * @mbggenerated Tue Mar 29 14:38:29 CST 2016
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_role.userid
     *
     * @mbggenerated Tue Mar 29 14:38:29 CST 2016
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_role.roleid
     *
     * @mbggenerated Tue Mar 29 14:38:29 CST 2016
     */
    private String roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_role.remark
     *
     * @mbggenerated Tue Mar 29 14:38:29 CST 2016
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_role.creator
     *
     * @mbggenerated Tue Mar 29 14:38:29 CST 2016
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_role.createdate
     *
     * @mbggenerated Tue Mar 29 14:38:29 CST 2016
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_role.updatetor
     *
     * @mbggenerated Tue Mar 29 14:38:29 CST 2016
     */
    private String updatetor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_role.updatedate
     *
     * @mbggenerated Tue Mar 29 14:38:29 CST 2016
     */
    private Date updatedate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_role.uuid
     *
     * @return the value of s_user_role.uuid
     *
     * @mbggenerated Tue Mar 29 14:38:29 CST 2016
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_role.uuid
     *
     * @param uuid the value for s_user_role.uuid
     *
     * @mbggenerated Tue Mar 29 14:38:29 CST 2016
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_role.userid
     *
     * @return the value of s_user_role.userid
     *
     * @mbggenerated Tue Mar 29 14:38:29 CST 2016
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_role.userid
     *
     * @param userid the value for s_user_role.userid
     *
     * @mbggenerated Tue Mar 29 14:38:29 CST 2016
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_role.roleid
     *
     * @return the value of s_user_role.roleid
     *
     * @mbggenerated Tue Mar 29 14:38:29 CST 2016
     */
    public String getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_role.roleid
     *
     * @param roleid the value for s_user_role.roleid
     *
     * @mbggenerated Tue Mar 29 14:38:29 CST 2016
     */
    public void setRoleid(String roleid) {
        this.roleid = roleid == null ? null : roleid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_role.remark
     *
     * @return the value of s_user_role.remark
     *
     * @mbggenerated Tue Mar 29 14:38:29 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_role.remark
     *
     * @param remark the value for s_user_role.remark
     *
     * @mbggenerated Tue Mar 29 14:38:29 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_role.creator
     *
     * @return the value of s_user_role.creator
     *
     * @mbggenerated Tue Mar 29 14:38:29 CST 2016
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_role.creator
     *
     * @param creator the value for s_user_role.creator
     *
     * @mbggenerated Tue Mar 29 14:38:29 CST 2016
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_role.createdate
     *
     * @return the value of s_user_role.createdate
     *
     * @mbggenerated Tue Mar 29 14:38:29 CST 2016
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_role.createdate
     *
     * @param createdate the value for s_user_role.createdate
     *
     * @mbggenerated Tue Mar 29 14:38:29 CST 2016
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_role.updatetor
     *
     * @return the value of s_user_role.updatetor
     *
     * @mbggenerated Tue Mar 29 14:38:29 CST 2016
     */
    public String getUpdatetor() {
        return updatetor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_role.updatetor
     *
     * @param updatetor the value for s_user_role.updatetor
     *
     * @mbggenerated Tue Mar 29 14:38:29 CST 2016
     */
    public void setUpdatetor(String updatetor) {
        this.updatetor = updatetor == null ? null : updatetor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_role.updatedate
     *
     * @return the value of s_user_role.updatedate
     *
     * @mbggenerated Tue Mar 29 14:38:29 CST 2016
     */
    public Date getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_role.updatedate
     *
     * @param updatedate the value for s_user_role.updatedate
     *
     * @mbggenerated Tue Mar 29 14:38:29 CST 2016
     */
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }
}