package com.evisible.os.controlcenter.system.dao;



import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.evisible.os.controlcenter.system.entity.SFun;
import com.evisible.os.controlcenter.system.entity.SFunExample;

public interface SFunMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_fun
     *
     * @mbggenerated Tue Mar 29 14:38:29 CST 2016
     */
    int countByExample(SFunExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_fun
     *
     * @mbggenerated Tue Mar 29 14:38:29 CST 2016
     */
    int deleteByExample(SFunExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_fun
     *
     * @mbggenerated Tue Mar 29 14:38:29 CST 2016
     */
    int deleteByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_fun
     *
     * @mbggenerated Tue Mar 29 14:38:29 CST 2016
     */
    int insert(SFun record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_fun
     *
     * @mbggenerated Tue Mar 29 14:38:29 CST 2016
     */
    int insertSelective(SFun record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_fun
     *
     * @mbggenerated Tue Mar 29 14:38:29 CST 2016
     */
    List<SFun> selectByExample(SFunExample example);
    
	    
	/**
	 * @see 查询功能列表
	 * @param value 查询参数
	 * @return 参数所满足的功能
	 */
	List<SFun> selectByExampleKZByValue(String value);
    
    /**
     * @see 对selectByExample进行扩展,并进行分组统计
     * @param example
     * @return FUNS
     * @author TENGDONG
     */  
   List<SFun>  selectToGroupByExample(Map<String,Object> example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_fun
     *
     * @mbggenerated Tue Mar 29 14:38:29 CST 2016
     */
    SFun selectByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_fun
     *
     * @mbggenerated Tue Mar 29 14:38:29 CST 2016
     */
    int updateByExampleSelective(@Param("record") SFun record, @Param("example") SFunExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_fun
     *
     * @mbggenerated Tue Mar 29 14:38:29 CST 2016
     */
    int updateByExample(@Param("record") SFun record, @Param("example") SFunExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_fun
     *
     * @mbggenerated Tue Mar 29 14:38:29 CST 2016
     */
    int updateByPrimaryKeySelective(SFun record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_fun
     *
     * @mbggenerated Tue Mar 29 14:38:29 CST 2016
     */
    int updateByPrimaryKey(SFun record);
    
    
}