package com.evisible.os.controlcenter.system.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.evisible.os.controlcenter.system.entity.SOrgUser;
import com.evisible.os.controlcenter.system.entity.SOrgUserExample;

public interface SOrgUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_org_user
     *
     * @mbggenerated Tue Aug 16 10:18:44 CST 2016
     */
    int countByExample(SOrgUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_org_user
     *
     * @mbggenerated Tue Aug 16 10:18:44 CST 2016
     */
    int deleteByExample(SOrgUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_org_user
     *
     * @mbggenerated Tue Aug 16 10:18:44 CST 2016
     */
    int deleteByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_org_user
     *
     * @mbggenerated Tue Aug 16 10:18:44 CST 2016
     */
    int insert(SOrgUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_org_user
     *
     * @mbggenerated Tue Aug 16 10:18:44 CST 2016
     */
    int insertSelective(SOrgUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_org_user
     *
     * @mbggenerated Tue Aug 16 10:18:44 CST 2016
     */
    List<SOrgUser> selectByExample(SOrgUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_org_user
     *
     * @mbggenerated Tue Aug 16 10:18:44 CST 2016
     */
    SOrgUser selectByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_org_user
     *
     * @mbggenerated Tue Aug 16 10:18:44 CST 2016
     */
    int updateByExampleSelective(@Param("record") SOrgUser record, @Param("example") SOrgUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_org_user
     *
     * @mbggenerated Tue Aug 16 10:18:44 CST 2016
     */
    int updateByExample(@Param("record") SOrgUser record, @Param("example") SOrgUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_org_user
     *
     * @mbggenerated Tue Aug 16 10:18:44 CST 2016
     */
    int updateByPrimaryKeySelective(SOrgUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_org_user
     *
     * @mbggenerated Tue Aug 16 10:18:44 CST 2016
     */
    int updateByPrimaryKey(SOrgUser record);
}