package com.evisible.os.controlcenter.system.dao;


import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.evisible.os.controlcenter.system.entity.SPermission;
import com.evisible.os.controlcenter.system.entity.SPermissionExample;

public interface SPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_permission
     *
     * @mbggenerated Mon Apr 18 09:45:30 CST 2016
     */
    int countByExample(SPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_permission
     *
     * @mbggenerated Mon Apr 18 09:45:30 CST 2016
     */
    int deleteByExample(SPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_permission
     *
     * @mbggenerated Mon Apr 18 09:45:30 CST 2016
     */
    int deleteByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_permission
     *
     * @mbggenerated Mon Apr 18 09:45:30 CST 2016
     */
    int insert(SPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_permission
     *
     * @mbggenerated Mon Apr 18 09:45:30 CST 2016
     */
    int insertSelective(SPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_permission
     *
     * @mbggenerated Mon Apr 18 09:45:30 CST 2016
     */
    List<SPermission> selectByExample(SPermissionExample example);
    
    
    /**
     * This method was generated by MyBatis TengDong.
     * This method corresponds to the database table s_permission
     *
     * @mbggenerated 20160414
     */
    List<SPermission> selectByExampleKZ11(Map<String,Object> example);  

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_permission
     *
     * @mbggenerated Mon Apr 18 09:45:30 CST 2016
     */
    SPermission selectByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_permission
     *
     * @mbggenerated Mon Apr 18 09:45:30 CST 2016
     */
    int updateByExampleSelective(@Param("record") SPermission record, @Param("example") SPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_permission
     *
     * @mbggenerated Mon Apr 18 09:45:30 CST 2016
     */
    int updateByExample(@Param("record") SPermission record, @Param("example") SPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_permission
     *
     * @mbggenerated Mon Apr 18 09:45:30 CST 2016
     */
    int updateByPrimaryKeySelective(SPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_permission
     *
     * @mbggenerated Mon Apr 18 09:45:30 CST 2016
     */
    int updateByPrimaryKey(SPermission record);
}