package com.evisible.os.controlcenter.system.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.evisible.os.controlcenter.system.entity.SRole;
import com.evisible.os.controlcenter.system.entity.SRoleExample;

public interface SRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role
     *
     * @mbggenerated Tue Mar 29 14:38:29 CST 2016
     */
    int countByExample(SRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role
     *
     * @mbggenerated Tue Mar 29 14:38:29 CST 2016
     */
    int deleteByExample(SRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role
     *
     * @mbggenerated Tue Mar 29 14:38:29 CST 2016
     */
    int deleteByPrimaryKey(String uuid);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role
     *
     * @mbggenerated Tue Mar 29 14:38:29 CST 2016
     */
    int insert(SRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role
     *
     * @mbggenerated Tue Mar 29 14:38:29 CST 2016
     */
    int insertSelective(SRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role
     *
     * @mbggenerated Tue Mar 29 14:38:29 CST 2016
     */
    List<SRole> selectByExample(SRoleExample example);
    
    /**
     * @author TengDong
     * @param example
     * @return
     */
    List<SRole> selectByExampleKZ(Map<String,Object> example);
    
    /**
     * @author TengDong
     * @param example
     * @return 
     */
    List<SRole> selectByExampleKZByUserId(String UserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role
     *
     * @mbggenerated Tue Mar 29 14:38:29 CST 2016
     */
    SRole selectByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role
     *
     * @mbggenerated Tue Mar 29 14:38:29 CST 2016
     */
    int updateByExampleSelective(@Param("record") SRole record, @Param("example") SRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role
     *
     * @mbggenerated Tue Mar 29 14:38:29 CST 2016
     */
    int updateByExample(@Param("record") SRole record, @Param("example") SRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role
     *
     * @mbggenerated Tue Mar 29 14:38:29 CST 2016
     */
    int updateByPrimaryKeySelective(SRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role
     *
     * @mbggenerated Tue Mar 29 14:38:29 CST 2016
     */
    int updateByPrimaryKey(SRole record);
}