package com.evisible.os.controlcenter.system.dao;


import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.evisible.os.controlcenter.system.entity.SysLog;
import com.evisible.os.controlcenter.system.entity.SysLogExample;

public interface SysLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_sys_log
     *
     * @mbggenerated Wed Apr 12 16:00:12 CST 2017
     */
    int countByExample(SysLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_sys_log
     *
     * @mbggenerated Wed Apr 12 16:00:12 CST 2017
     */
    int deleteByExample(SysLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_sys_log
     *
     * @mbggenerated Wed Apr 12 16:00:12 CST 2017
     */
    int deleteByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_sys_log
     *
     * @mbggenerated Wed Apr 12 16:00:12 CST 2017
     */
    int insert(SysLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_sys_log
     *
     * @mbggenerated Wed Apr 12 16:00:12 CST 2017
     */
    int insertSelective(SysLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_sys_log
     *
     * @mbggenerated Wed Apr 12 16:00:12 CST 2017
     */
    List<SysLog> selectByExample(SysLogExample example);
    
    
    /**
     * @see 时间段获取系统日志
     * @author TengDong
     * @param example map
     * @return SysLogs
     */
    List<SysLog> selectByExampleKZ(Map<String,Object> example);
    
    /**
     * @param example 统计
     * @return int
     */
    int countSelectByExampleKZ(Map<String,Object> example);
    

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_sys_log
     *
     * @mbggenerated Wed Apr 12 16:00:12 CST 2017
     */
    SysLog selectByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_sys_log
     *
     * @mbggenerated Wed Apr 12 16:00:12 CST 2017
     */
    int updateByExampleSelective(@Param("record") SysLog record, @Param("example") SysLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_sys_log
     *
     * @mbggenerated Wed Apr 12 16:00:12 CST 2017
     */
    int updateByExample(@Param("record") SysLog record, @Param("example") SysLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_sys_log
     *
     * @mbggenerated Wed Apr 12 16:00:12 CST 2017
     */
    int updateByPrimaryKeySelective(SysLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_sys_log
     *
     * @mbggenerated Wed Apr 12 16:00:12 CST 2017
     */
    int updateByPrimaryKey(SysLog record);
}